# Hugo Configuration
# Documentation: https://gohugo.io/getting-started/configuration/

title: 'Baecher Research'
baseURL: 'https://alexbaecher.com'
copyright: '© {year} Alex Baecher'
defaultContentLanguage: 'en'
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

# Hugo Modules
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

build:
  writeStats: true

# Page settings
summaryLength: 30
enableEmoji: true
enableGitInfo: false
footnoteReturnLinkContents: '<sup>^</sup>'

ignoreFiles:
  - '\.ipynb$'
  - '.ipynb_checkpoints$'
  - '\.Rmd$'
  - '\.Rmarkdown$'
  - '_cache$'

# URL structure
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

# Output formats
outputs:
  home: ['HTML', 'RSS', 'headers', 'redirects']
  section: ['HTML', 'RSS']
 
# Page limits 
params:
  'pagination.pagerSize': 10

# Media types
mediaTypes:
  'text/netlify': 
    suffixes: ['']
    delimiter: ''

# Custom output formats
outputFormats:
  headers:
    mediaType: 'text/netlify'
    baseName: '_headers'
    isPlainText: true
    notAlternative: true
  redirects:
    mediaType: 'text/netlify'
    baseName: '_redirects'
    isPlainText: true
    notAlternative: true

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
    noClasses: false
    style: github
  tableOfContents:
    startLevel: 2
    endLevel: 3

# Image processing
imaging:
  resampleFilter: 'Lanczos'
  quality: 90
  anchor: 'Smart'

# Taxonomies
taxonomies:
  tag: 'tags'
  category: 'categories'
  author: 'authors'
  publication_type: 'publication_types'

# Related content
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: 'title'
      weight: 60
    - name: 'summary'
      weight: 50
    - name: 'tags'
      weight: 80
    - name: 'categories'
      weight: 70
    - name: 'authors'
      weight: 20

# Security
security:
  enableInlineShortcodes: false
  funcs:
    getenv: ['^HUGO_', '^WC_']
