main:
  - name: Home
    url: '/'
    weight: 10
  - name: Team
    url: '/people/'
    weight: 20
  - name: Research
    url: '/project/'
    weight: 30
  - name: Publications
    url: '/publication/'
    weight: 40
  - name: Talks
    url: '/talk/'
    weight: 50
  - name: Tutorials
    url: '/post/'
    weight: 60
  - name: Contact
    url: '/#contact'
    weight: 70