# Website theme and appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# SEO and site info
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Baecher research"
    twitter: 'AlexBaecher'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© {year} Alex Baecher. All rights reserved.'
    license:
      enable: false
  block:
    enable: false
  powered_by:
    enable: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/slamander/alexbaecher-website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    commentable:
      post: true
      book: true
      project: true
      publication: true
      event: true
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''

# Contact details
contact:
  # Contact form provider
  form:
    provider: netlify
    formspree:
      id: ''
    netlify:
      # Enable CAPTCHA challenge to reduce spam?
      captcha: false
  # Email for contact form and footer
  email: jbaecher@gmail.com
  phone: '352-226-3983'
  address:
    street: 
    city: Gainesville
    region: FL
    postcode: '32601'
    country: United States
    country_code: US
  coordinates:
    latitude: 
    longitude: 
  contact_links:
    - icon: envelope
      icon_pack: fas
      name: Email
      link: 'mailto:jbaecher@gmail.com'
    - icon: twitter
      icon_pack: fab
      name: Twitter
      link: 'https://twitter.com/AlexBaecher'
    - icon: instagram
      icon_pack: fab
      name: Instagram
      link: 'https://instagram.com/j_baecher'

# Site search
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

# Maps
map:
  provider: 'mapnik'
  api_key: ''
  zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  highlight:
    enable: true
    languages:
      r: true
